package wang.raye.springboot.model;

public class AlertSetting {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_setting.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_setting.exchange
     *
     * @mbg.generated
     */
    private String exchange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_setting.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_setting.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_setting.period
     *
     * @mbg.generated
     */
    private String period;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_setting.openflg
     *
     * @mbg.generated
     */
    private String openflg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_setting.id
     *
     * @return the value of alert_setting.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_setting.id
     *
     * @param id the value for alert_setting.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_setting.exchange
     *
     * @return the value of alert_setting.exchange
     *
     * @mbg.generated
     */
    public String getExchange() {
        return exchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_setting.exchange
     *
     * @param exchange the value for alert_setting.exchange
     *
     * @mbg.generated
     */
    public void setExchange(String exchange) {
        this.exchange = exchange == null ? null : exchange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_setting.type
     *
     * @return the value of alert_setting.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_setting.type
     *
     * @param type the value for alert_setting.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_setting.status
     *
     * @return the value of alert_setting.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_setting.status
     *
     * @param status the value for alert_setting.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_setting.period
     *
     * @return the value of alert_setting.period
     *
     * @mbg.generated
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_setting.period
     *
     * @param period the value for alert_setting.period
     *
     * @mbg.generated
     */
    public void setPeriod(String period) {
        this.period = period == null ? null : period.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_setting.openflg
     *
     * @return the value of alert_setting.openflg
     *
     * @mbg.generated
     */
    public String getOpenflg() {
        return openflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_setting.openflg
     *
     * @param openflg the value for alert_setting.openflg
     *
     * @mbg.generated
     */
    public void setOpenflg(String openflg) {
        this.openflg = openflg == null ? null : openflg.trim();
    }
}