package wang.raye.springboot.model;

public class AlertUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_user.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_user.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_user.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_user.sckey
     *
     * @mbg.generated
     */
    private String sckey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_user.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_user.openflg
     *
     * @mbg.generated
     */
    private String openflg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_user.id
     *
     * @return the value of alert_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_user.id
     *
     * @param id the value for alert_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_user.role_id
     *
     * @return the value of alert_user.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_user.role_id
     *
     * @param roleId the value for alert_user.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_user.user_id
     *
     * @return the value of alert_user.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_user.user_id
     *
     * @param userId the value for alert_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_user.user_name
     *
     * @return the value of alert_user.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_user.user_name
     *
     * @param userName the value for alert_user.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_user.sckey
     *
     * @return the value of alert_user.sckey
     *
     * @mbg.generated
     */
    public String getSckey() {
        return sckey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_user.sckey
     *
     * @param sckey the value for alert_user.sckey
     *
     * @mbg.generated
     */
    public void setSckey(String sckey) {
        this.sckey = sckey == null ? null : sckey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_user.status
     *
     * @return the value of alert_user.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_user.status
     *
     * @param status the value for alert_user.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_user.openflg
     *
     * @return the value of alert_user.openflg
     *
     * @mbg.generated
     */
    public String getOpenflg() {
        return openflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_user.openflg
     *
     * @param openflg the value for alert_user.openflg
     *
     * @mbg.generated
     */
    public void setOpenflg(String openflg) {
        this.openflg = openflg == null ? null : openflg.trim();
    }
}