package wang.raye.springboot.model;

import java.util.Date;

public class MacdCross {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.exchange
     *
     * @mbg.generated
     */
    private String exchange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.symbol
     *
     * @mbg.generated
     */
    private String symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.quota1
     *
     * @mbg.generated
     */
    private Double quota1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.quota2
     *
     * @mbg.generated
     */
    private Double quota2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.quota3
     *
     * @mbg.generated
     */
    private Double quota3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.price
     *
     * @mbg.generated
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.period
     *
     * @mbg.generated
     */
    private String period;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.id
     *
     * @return the value of macd_cross.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.id
     *
     * @param id the value for macd_cross.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.exchange
     *
     * @return the value of macd_cross.exchange
     *
     * @mbg.generated
     */
    public String getExchange() {
        return exchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.exchange
     *
     * @param exchange the value for macd_cross.exchange
     *
     * @mbg.generated
     */
    public void setExchange(String exchange) {
        this.exchange = exchange == null ? null : exchange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.symbol
     *
     * @return the value of macd_cross.symbol
     *
     * @mbg.generated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.symbol
     *
     * @param symbol the value for macd_cross.symbol
     *
     * @mbg.generated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.type
     *
     * @return the value of macd_cross.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.type
     *
     * @param type the value for macd_cross.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.status
     *
     * @return the value of macd_cross.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.status
     *
     * @param status the value for macd_cross.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.quota1
     *
     * @return the value of macd_cross.quota1
     *
     * @mbg.generated
     */
    public Double getQuota1() {
        return quota1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.quota1
     *
     * @param quota1 the value for macd_cross.quota1
     *
     * @mbg.generated
     */
    public void setQuota1(Double quota1) {
        this.quota1 = quota1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.quota2
     *
     * @return the value of macd_cross.quota2
     *
     * @mbg.generated
     */
    public Double getQuota2() {
        return quota2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.quota2
     *
     * @param quota2 the value for macd_cross.quota2
     *
     * @mbg.generated
     */
    public void setQuota2(Double quota2) {
        this.quota2 = quota2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.quota3
     *
     * @return the value of macd_cross.quota3
     *
     * @mbg.generated
     */
    public Double getQuota3() {
        return quota3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.quota3
     *
     * @param quota3 the value for macd_cross.quota3
     *
     * @mbg.generated
     */
    public void setQuota3(Double quota3) {
        this.quota3 = quota3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.price
     *
     * @return the value of macd_cross.price
     *
     * @mbg.generated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.price
     *
     * @param price the value for macd_cross.price
     *
     * @mbg.generated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.period
     *
     * @return the value of macd_cross.period
     *
     * @mbg.generated
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.period
     *
     * @param period the value for macd_cross.period
     *
     * @mbg.generated
     */
    public void setPeriod(String period) {
        this.period = period == null ? null : period.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.time
     *
     * @return the value of macd_cross.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.time
     *
     * @param time the value for macd_cross.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }
}