package wang.raye.springboot.model;

import java.util.Date;

public class Schedule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.exchange
     *
     * @mbg.generated
     */
    private String exchange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.period
     *
     * @mbg.generated
     */
    private String period;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.intervals
     *
     * @mbg.generated
     */
    private String intervals;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.lasttime
     *
     * @mbg.generated
     */
    private Date lasttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.id
     *
     * @return the value of schedule.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.id
     *
     * @param id the value for schedule.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.exchange
     *
     * @return the value of schedule.exchange
     *
     * @mbg.generated
     */
    public String getExchange() {
        return exchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.exchange
     *
     * @param exchange the value for schedule.exchange
     *
     * @mbg.generated
     */
    public void setExchange(String exchange) {
        this.exchange = exchange == null ? null : exchange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.period
     *
     * @return the value of schedule.period
     *
     * @mbg.generated
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.period
     *
     * @param period the value for schedule.period
     *
     * @mbg.generated
     */
    public void setPeriod(String period) {
        this.period = period == null ? null : period.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.intervals
     *
     * @return the value of schedule.intervals
     *
     * @mbg.generated
     */
    public String getIntervals() {
        return intervals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.intervals
     *
     * @param intervals the value for schedule.intervals
     *
     * @mbg.generated
     */
    public void setIntervals(String intervals) {
        this.intervals = intervals == null ? null : intervals.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.status
     *
     * @return the value of schedule.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.status
     *
     * @param status the value for schedule.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.lasttime
     *
     * @return the value of schedule.lasttime
     *
     * @mbg.generated
     */
    public Date getLasttime() {
        return lasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.lasttime
     *
     * @param lasttime the value for schedule.lasttime
     *
     * @mbg.generated
     */
    public void setLasttime(Date lasttime) {
        this.lasttime = lasttime;
    }
}