package wang.raye.springboot.model.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import wang.raye.springboot.model.AlertUser;
import wang.raye.springboot.model.AlertUserCriteria;

public interface AlertUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_user
     *
     * @mbg.generated
     */
    @SelectProvider(type=AlertUserSqlProvider.class, method="countByExample")
    long countByExample(AlertUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_user
     *
     * @mbg.generated
     */
    @DeleteProvider(type=AlertUserSqlProvider.class, method="deleteByExample")
    int deleteByExample(AlertUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_user
     *
     * @mbg.generated
     */
    @Delete({
        "delete from alert_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_user
     *
     * @mbg.generated
     */
    @Insert({
        "insert into alert_user (id, role_id, ",
        "user_id, user_name, ",
        "sckey, status, openflg)",
        "values (#{id,jdbcType=INTEGER}, #{roleId,jdbcType=INTEGER}, ",
        "#{userId,jdbcType=INTEGER}, #{userName,jdbcType=VARCHAR}, ",
        "#{sckey,jdbcType=VARCHAR}, #{status,jdbcType=CHAR}, #{openflg,jdbcType=CHAR})"
    })
    int insert(AlertUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_user
     *
     * @mbg.generated
     */
    @InsertProvider(type=AlertUserSqlProvider.class, method="insertSelective")
    int insertSelective(AlertUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_user
     *
     * @mbg.generated
     */
    @SelectProvider(type=AlertUserSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="role_id", property="roleId", jdbcType=JdbcType.INTEGER),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="sckey", property="sckey", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.CHAR),
        @Result(column="openflg", property="openflg", jdbcType=JdbcType.CHAR)
    })
    List<AlertUser> selectByExample(AlertUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_user
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, role_id, user_id, user_name, sckey, status, openflg",
        "from alert_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="role_id", property="roleId", jdbcType=JdbcType.INTEGER),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="sckey", property="sckey", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.CHAR),
        @Result(column="openflg", property="openflg", jdbcType=JdbcType.CHAR)
    })
    AlertUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_user
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AlertUserSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") AlertUser record, @Param("example") AlertUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_user
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AlertUserSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") AlertUser record, @Param("example") AlertUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_user
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AlertUserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(AlertUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_user
     *
     * @mbg.generated
     */
    @Update({
        "update alert_user",
        "set role_id = #{roleId,jdbcType=INTEGER},",
          "user_id = #{userId,jdbcType=INTEGER},",
          "user_name = #{userName,jdbcType=VARCHAR},",
          "sckey = #{sckey,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=CHAR},",
          "openflg = #{openflg,jdbcType=CHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(AlertUser record);
}