package wang.raye.springboot.model.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import wang.raye.springboot.model.AlertSetting;
import wang.raye.springboot.model.AlertSettingCriteria;

public interface AlertSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_setting
     *
     * @mbg.generated
     */
    @SelectProvider(type=AlertSettingSqlProvider.class, method="countByExample")
    long countByExample(AlertSettingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_setting
     *
     * @mbg.generated
     */
    @DeleteProvider(type=AlertSettingSqlProvider.class, method="deleteByExample")
    int deleteByExample(AlertSettingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_setting
     *
     * @mbg.generated
     */
    @Delete({
        "delete from alert_setting",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_setting
     *
     * @mbg.generated
     */
    @Insert({
        "insert into alert_setting (id, exchange, ",
        "type, status, period, ",
        "openflg)",
        "values (#{id,jdbcType=INTEGER}, #{exchange,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=VARCHAR}, #{status,jdbcType=CHAR}, #{period,jdbcType=VARCHAR}, ",
        "#{openflg,jdbcType=CHAR})"
    })
    int insert(AlertSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_setting
     *
     * @mbg.generated
     */
    @InsertProvider(type=AlertSettingSqlProvider.class, method="insertSelective")
    int insertSelective(AlertSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_setting
     *
     * @mbg.generated
     */
    @SelectProvider(type=AlertSettingSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="exchange", property="exchange", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.CHAR),
        @Result(column="period", property="period", jdbcType=JdbcType.VARCHAR),
        @Result(column="openflg", property="openflg", jdbcType=JdbcType.CHAR)
    })
    List<AlertSetting> selectByExample(AlertSettingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_setting
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, exchange, type, status, period, openflg",
        "from alert_setting",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="exchange", property="exchange", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.CHAR),
        @Result(column="period", property="period", jdbcType=JdbcType.VARCHAR),
        @Result(column="openflg", property="openflg", jdbcType=JdbcType.CHAR)
    })
    AlertSetting selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_setting
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AlertSettingSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") AlertSetting record, @Param("example") AlertSettingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_setting
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AlertSettingSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") AlertSetting record, @Param("example") AlertSettingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_setting
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AlertSettingSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(AlertSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_setting
     *
     * @mbg.generated
     */
    @Update({
        "update alert_setting",
        "set exchange = #{exchange,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=CHAR},",
          "period = #{period,jdbcType=VARCHAR},",
          "openflg = #{openflg,jdbcType=CHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(AlertSetting record);
}