package wang.raye.springboot.model.mapper;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import wang.raye.springboot.model.MacdCrossHistory;
import wang.raye.springboot.model.MacdCrossHistoryCriteria;

import java.util.List;

public interface MacdCrossHistoryMapperCustom {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table macd_cross_history
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, exchange, symbol, type, status, quota1, quota2, quota3, price, period, time",
        "from macd_cross_history",
        "where id = #{id,jdbcType=INTEGER}",
        "SELECT",
        "	A.*",
        "FROM",
        "	macd_cross_history A,",
        "	(",
        "		SELECT",
        "			id,",
        "			exchange,",
        "			symbol,",
        "			type,",
        "			period,",
        "			status,",
        "			MAX(time) max_day",
        "		FROM",
        "			macd_cross_history",
        "		WHERE",
        "			type = #{type,jdbcType=VARCHAR}",
        "		AND exchange = #{exchange,jdbcType=VARCHAR}",
        "		AND symbol LIKE #{symbol,jdbcType=VARCHAR}",
        "		AND period = #{period,jdbcType=VARCHAR}",
        "		AND status = #{status,jdbcType=CHAR}",
        "		GROUP BY",
        "			exchange,",
        "			symbol,",
        "			type,",
        "			period",
        "		ORDER BY",
        "			symbol ASC",
        "	) B",
        "WHERE",
        "	A.symbol = B.symbol",
        "AND A.exchange = B.exchange",
        "AND A.type = B.type",
        "AND A.status = B.status",
        "AND A.period = B.period",
        "AND A.time = B.max_day",
        "ORDER BY",
        "	A.symbol ASC"

    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="exchange", property="exchange", jdbcType=JdbcType.VARCHAR),
        @Result(column="symbol", property="symbol", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.CHAR),
        @Result(column="quota1", property="quota1", jdbcType=JdbcType.DOUBLE),
        @Result(column="quota2", property="quota2", jdbcType=JdbcType.DOUBLE),
        @Result(column="quota3", property="quota3", jdbcType=JdbcType.DOUBLE),
        @Result(column="price", property="price", jdbcType=JdbcType.DOUBLE),
        @Result(column="period", property="period", jdbcType=JdbcType.VARCHAR),
        @Result(column="time", property="time", jdbcType=JdbcType.TIMESTAMP)
    })
    MacdCrossHistory selectBySymbol(String exchange, String symbol, String type, String status, String period);



}