package wang.raye.springboot.model.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import wang.raye.springboot.model.Schedule;
import wang.raye.springboot.model.ScheduleCriteria;

public interface ScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    @SelectProvider(type=ScheduleSqlProvider.class, method="countByExample")
    long countByExample(ScheduleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    @DeleteProvider(type=ScheduleSqlProvider.class, method="deleteByExample")
    int deleteByExample(ScheduleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    @Delete({
        "delete from schedule",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    @Insert({
        "insert into schedule (id, exchange, ",
        "period, intervals, ",
        "status, lasttime)",
        "values (#{id,jdbcType=INTEGER}, #{exchange,jdbcType=VARCHAR}, ",
        "#{period,jdbcType=VARCHAR}, #{intervals,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=INTEGER}, #{lasttime,jdbcType=TIMESTAMP})"
    })
    int insert(Schedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    @InsertProvider(type=ScheduleSqlProvider.class, method="insertSelective")
    int insertSelective(Schedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    @SelectProvider(type=ScheduleSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="exchange", property="exchange", jdbcType=JdbcType.VARCHAR),
        @Result(column="period", property="period", jdbcType=JdbcType.VARCHAR),
        @Result(column="intervals", property="intervals", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="lasttime", property="lasttime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Schedule> selectByExample(ScheduleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, exchange, period, intervals, status, lasttime",
        "from schedule",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="exchange", property="exchange", jdbcType=JdbcType.VARCHAR),
        @Result(column="period", property="period", jdbcType=JdbcType.VARCHAR),
        @Result(column="intervals", property="intervals", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="lasttime", property="lasttime", jdbcType=JdbcType.TIMESTAMP)
    })
    Schedule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ScheduleSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Schedule record, @Param("example") ScheduleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ScheduleSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Schedule record, @Param("example") ScheduleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    @UpdateProvider(type=ScheduleSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Schedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated
     */
    @Update({
        "update schedule",
        "set exchange = #{exchange,jdbcType=VARCHAR},",
          "period = #{period,jdbcType=VARCHAR},",
          "intervals = #{intervals,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "lasttime = #{lasttime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Schedule record);
}