package wang.raye.springboot.model.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import wang.raye.springboot.model.Symbols;
import wang.raye.springboot.model.SymbolsCriteria;

public interface SymbolsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symbols
     *
     * @mbg.generated
     */
    @SelectProvider(type=SymbolsSqlProvider.class, method="countByExample")
    long countByExample(SymbolsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symbols
     *
     * @mbg.generated
     */
    @DeleteProvider(type=SymbolsSqlProvider.class, method="deleteByExample")
    int deleteByExample(SymbolsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symbols
     *
     * @mbg.generated
     */
    @Delete({
        "delete from symbols",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symbols
     *
     * @mbg.generated
     */
    @Insert({
        "insert into symbols (id, exchange, ",
        "symbol, price, time)",
        "values (#{id,jdbcType=INTEGER}, #{exchange,jdbcType=VARCHAR}, ",
        "#{symbol,jdbcType=VARCHAR}, #{price,jdbcType=DOUBLE}, #{time,jdbcType=TIMESTAMP})"
    })
    int insert(Symbols record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symbols
     *
     * @mbg.generated
     */
    @InsertProvider(type=SymbolsSqlProvider.class, method="insertSelective")
    int insertSelective(Symbols record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symbols
     *
     * @mbg.generated
     */
    @SelectProvider(type=SymbolsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="exchange", property="exchange", jdbcType=JdbcType.VARCHAR),
        @Result(column="symbol", property="symbol", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.DOUBLE),
        @Result(column="time", property="time", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Symbols> selectByExample(SymbolsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symbols
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, exchange, symbol, price, time",
        "from symbols",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="exchange", property="exchange", jdbcType=JdbcType.VARCHAR),
        @Result(column="symbol", property="symbol", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.DOUBLE),
        @Result(column="time", property="time", jdbcType=JdbcType.TIMESTAMP)
    })
    Symbols selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symbols
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SymbolsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Symbols record, @Param("example") SymbolsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symbols
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SymbolsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Symbols record, @Param("example") SymbolsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symbols
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SymbolsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Symbols record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symbols
     *
     * @mbg.generated
     */
    @Update({
        "update symbols",
        "set exchange = #{exchange,jdbcType=VARCHAR},",
          "symbol = #{symbol,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=DOUBLE},",
          "time = #{time,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Symbols record);
}